CREATE DATABASE [Dashboard]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Dashboard', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SERVIDOR\MSSQL\DATA\Dashboard.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Dashboard_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SERVIDOR\MSSQL\DATA\Dashboard_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [Dashboard] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [Dashboard] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Dashboard] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Dashboard] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Dashboard] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Dashboard] SET ARITHABORT OFF 
GO
ALTER DATABASE [Dashboard] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Dashboard] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Dashboard] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [Dashboard] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Dashboard] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Dashboard] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Dashboard] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Dashboard] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Dashboard] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Dashboard] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Dashboard] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Dashboard] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Dashboard] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Dashboard] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Dashboard] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Dashboard] SET  READ_WRITE 
GO
ALTER DATABASE [Dashboard] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Dashboard] SET  MULTI_USER 
GO
ALTER DATABASE [Dashboard] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Dashboard] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Dashboard] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Dashboard]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [Dashboard]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Dashboard] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO


USE [master]
GO
CREATE LOGIN [user_dashboard] WITH PASSWORD=N'user_dashboard', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [Dashboard]
GO
CREATE USER [user_dashboard] FOR LOGIN [user_dashboard]
GO
USE [Dashboard]
GO
ALTER ROLE [db_owner] ADD MEMBER [user_dashboard]
GO


CREATE TABLE Users
(
    Id uniqueidentifier NOT NULL
        CONSTRAINT PK_Users PRIMARY KEY
        DEFAULT NEWSEQUENTIALID(),

    Email nvarchar(320) NOT NULL,

    PasswordHash nvarchar(500) NOT NULL,

    CreatedAt datetime2 NOT NULL
        CONSTRAINT DF_Users_CreatedAt
        DEFAULT SYSUTCDATETIME(),

    UpdatedAt datetime2 NOT NULL
        CONSTRAINT DF_Users_UpdatedAt
        DEFAULT SYSUTCDATETIME()

		UNIQUE (Email)
);



CREATE TABLE Boards
(
    Id uniqueidentifier NOT NULL
        CONSTRAINT PK_Boards PRIMARY KEY
        DEFAULT NEWSEQUENTIALID(),

    OwnerId uniqueidentifier NOT NULL,

    Name nvarchar(200) NOT NULL,

    CreatedAt datetime2 NOT NULL
        CONSTRAINT DF_Boards_CreatedAt
        DEFAULT SYSUTCDATETIME(),

    UpdatedAt datetime2 NOT NULL
        CONSTRAINT DF_Boards_UpdatedAt
        DEFAULT SYSUTCDATETIME(),

    CONSTRAINT FK_Boards_Users
        FOREIGN KEY (OwnerId)
        REFERENCES Users(Id)
);

CREATE TABLE BoardItems
(
    Id uniqueidentifier NOT NULL
        CONSTRAINT PK_BoardItems PRIMARY KEY
        DEFAULT NEWSEQUENTIALID(),

    BoardId uniqueidentifier NOT NULL,

    Type nvarchar(50) NOT NULL,

    Data nvarchar(max) NOT NULL,

    PositionX float NOT NULL,
    PositionY float NOT NULL,

    Width float NOT NULL,
    Height float NOT NULL,

    CreatedAt datetime2 NOT NULL
        CONSTRAINT DF_BoardItems_CreatedAt
        DEFAULT SYSUTCDATETIME(),

    UpdatedAt datetime2 NOT NULL
        CONSTRAINT DF_BoardItems_UpdatedAt
        DEFAULT SYSUTCDATETIME(),

    CONSTRAINT FK_BoardItems_Boards
        FOREIGN KEY (BoardId)
        REFERENCES Boards(Id)
);

CREATE TABLE BoardPermissions
(
    Id uniqueidentifier NOT NULL
        CONSTRAINT PK_BoardPermissions PRIMARY KEY
        DEFAULT NEWSEQUENTIALID(),

    BoardId uniqueidentifier NOT NULL,

    UserId uniqueidentifier NOT NULL,

    Role nvarchar(20) NOT NULL,

    CreatedAt datetime2 NOT NULL
        CONSTRAINT DF_BoardPermissions_CreatedAt
        DEFAULT SYSUTCDATETIME(),

    CONSTRAINT FK_BoardPermissions_Boards
        FOREIGN KEY (BoardId)
        REFERENCES Boards(Id),

    CONSTRAINT FK_BoardPermissions_Users
        FOREIGN KEY (UserId)
        REFERENCES Users(Id)

);



--dotnet ef migrations add InitialCreate
--dotnet ef database update